apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-deployment
  labels:
    app: spring-boot 
spec:
  replicas: 1
  strategy:
     type: Recreate
  selector:
    matchLabels:
      app: spring-boot 
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - name: spring-boot 
        image: spring-boot:1.14.2
        ports:
        - containerPort: 80
      liveliness:
        delay: 60
      readiness:
        delay: 60
